name: admin_dashboard_myfuture
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

#firebase
  firebase_core: ^3.11.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.3
  get: ^4.7.2

#date, graph
  intl: ^0.20.2
  fl_chart: ^1.1.1

  cupertino_icons: ^1.0.8

#image upload
  firebase_storage: ^12.4.10
  image_picker: ^1.2.1

#image_crop
  image_cropper: ^11.0.0
  pdf: ^3.11.3
  printing: ^5.14.2

#url 
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/logo/myfuture_logo.png
    - .env

